### ISSUE TITLE
Updates for the list of additional requirement

### ISSUE THREAD

**Issue by pilot** [pilot/sales-report#4]
- в этой форме `/sales/request` при заполнении адреса русскими буквами ошибка не показывается. Просто ничего не происходит. 
  - добавить ошибку "Пожалуйста, укажите корректный e-mail"
- в списках регионах в форме не хватает двух регионов Мордовии и Северной осетии. 
- регионы в выпадающем списке сортировать по алфавиту
- текст с абзаца
  - /sales/add/ перед словами Многие и перед Чтобы
  - /sales/request/  в самом начале и перед словами "Если у Вас есть вопросы..."
- /sales/list - добавить редактирование / удаление

**Comment by barik94** [comment]
11.12 - 0.75h
14.12 - 4.25h
15.12 - 0.5h
